### ISSUE TITLE
not outputting final file

### ISSUE THREAD

**Issue by VinSpee** [btd/image-optim#1]
Hi!

I'm trying to use your script, but having issues actually getting it to output a new file. Here's my setup:

``` js
var Opti = require('img-optim');
var glob = require('glob');

var args = process.argv.slice(2);
var output = args[1];
var input = args[0];

var opti = new Opti();

glob(input, function(err, files) {
    console.log(err, files);
    opti.run(files, function(err, files) {
        console.log(err, files);
    });
});
```

here's what I get logged:

``` bash
null [ './src/images/Screen Shot 2015-07-09 at 8.56.26 AM.png' ]
null [ '/var/folders/h1/sz78f2z55dv65fv0nx0x_jvc077wx1/T/tmp-68065srqlsyo.png' ]
```

How can I output the file to a directory while keeping the filename?

Thanks for your great work!

**Comment by btd** [comment]
Hello, when i did it i had no such task in keeping names. You can either: use options.replace = true to do optimization in place of file, second option is just rename files - all files should be in the same order as they was in original array.

**Comment by VinSpee** [comment]
Okay, thanks!
